# Generated by Django 4.0.5 on 2022-09-30 18:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dfrm_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/blog/')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('snippet', ckeditor.fields.RichTextField(max_length=255)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('primary_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='dfrm_admin.employee')),
                ('secondary_authors', models.ManyToManyField(related_name='other_authors', to='dfrm_admin.employee')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_upload', to='dfrm_admin.employee')),
            ],
        ),
    ]
