# Generated by Django 4.0.5 on 2023-05-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(upload_to='images/blog/'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
