# Generated by Django 4.0.5 on 2022-09-30 18:28

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Division name', max_length=300)),
                ('description', models.TextField(help_text='Division description')),
                ('division_image1', models.ImageField(blank=True, null=True, upload_to='images/division/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_class', models.SmallIntegerField(choices=[(9, 'Administrative Specialist I'), (11, 'Administrative Specialist II'), (13, 'Administrative Specialist III'), (15, 'Executive Assistant I'), (9, 'Technician I'), (11, 'Technician II'), (13, 'Technician III'), (15, 'Technician IV'), (17, 'Professional I'), (19, 'Professional II'), (20, 'Professional III'), (21, 'Professional IV'), (22, 'Project Leader V'), (23, 'Manager I'), (24, 'Manager II'), (26, 'Manager III'), (28, 'Manager IV'), (30, 'Manager V')], help_text='Position class')),
                ('title', models.CharField(help_text='Position title', max_length=50)),
                ('active', models.BooleanField(default=False, help_text='Is the employee actively employed?')),
                ('name', models.OneToOneField(help_text='Employee name', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Office name', max_length=100)),
                ('phone_number', phone_field.models.PhoneField(help_text='Phone number', max_length=31)),
                ('fax_number', phone_field.models.PhoneField(blank=True, help_text='Fax number', max_length=31, null=True)),
                ('address', models.CharField(help_text='Street address', max_length=100)),
                ('city', models.CharField(help_text='City', max_length=50)),
                ('state', models.CharField(help_text='State', max_length=50)),
                ('zipcode', models.CharField(help_text='Zip Code', max_length=5)),
                ('office_image', models.ImageField(blank=True, upload_to='images/office/')),
                ('administrative_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_assistants', to='dfrm_admin.employee')),
                ('office_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='dfrm_admin.employee')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=300)),
                ('description', models.TextField(help_text='Project description')),
                ('created', models.DateTimeField(help_text='When was the project created?')),
                ('active', models.BooleanField(help_text='Is the project currently active?')),
                ('project_image1', models.ImageField(blank=True, null=True, upload_to='images/project/')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.division')),
                ('office', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.office')),
                ('project_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_leads', to='dfrm_admin.employee')),
                ('staff', models.ManyToManyField(blank=True, to='dfrm_admin.employee')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='administrative_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_support', to='dfrm_admin.employee'),
        ),
        migrations.AddField(
            model_name='division',
            name='deputy_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_deputies', to='dfrm_admin.employee'),
        ),
        migrations.AddField(
            model_name='division',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_directors', to='dfrm_admin.employee'),
        ),
        migrations.AddField(
            model_name='division',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_offices', to='dfrm_admin.office'),
        ),
    ]
