# Generated by Django 4.0.5 on 2022-10-14 21:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Department name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Department desecription')),
                ('department_image1', models.ImageField(blank=True, null=True, upload_to='images/department/', verbose_name='Department Image')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Position title')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PositionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_class', models.CharField(max_length=50)),
                ('grade', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Project name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Project description')),
                ('created', models.DateTimeField(verbose_name='Created')),
                ('active', models.BooleanField(verbose_name='Active')),
                ('project_image1', models.ImageField(blank=True, null=True, upload_to='images/project/', verbose_name='Project image')),
                ('project_leader', models.ManyToManyField(to='dfrm_admin.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Subproject name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Subproject description')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.project')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sup', to='dfrm_admin.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Task name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Task description')),
                ('staff', models.ManyToManyField(blank=True, related_name='staff', to='dfrm_admin.employee')),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.subproject')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sup', to='dfrm_admin.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Office name')),
                ('phone_number', phone_field.models.PhoneField(max_length=31, verbose_name='Phone number')),
                ('fax_number', phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Fax number')),
                ('street_address', models.CharField(max_length=100, verbose_name='Street address')),
                ('mailing_address', models.CharField(max_length=100, verbose_name='Mailing address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('zipcode', models.CharField(max_length=5, verbose_name='Zip Code')),
                ('office_image', models.ImageField(blank=True, upload_to='images/office/', verbose_name='Office image')),
                ('administrative_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_assist', to='dfrm_admin.employee')),
                ('office_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_manager', to='dfrm_admin.employee')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.positionclass'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Division name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Division desecription')),
                ('division_image1', models.ImageField(blank=True, null=True, upload_to='images/division/', verbose_name='Division Image')),
                ('administrative_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div_assist', to='dfrm_admin.employee')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.department')),
                ('deputy_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div_deputy', to='dfrm_admin.employee')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='div_director', to='dfrm_admin.employee')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.office')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='administrative_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_assist', to='dfrm_admin.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='deputy_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_deputy', to='dfrm_admin.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_manager', to='dfrm_admin.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.office'),
        ),
    ]
