# Generated by Django 4.0.5 on 2022-10-06 16:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfrm_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Division description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Project description'),
        ),
    ]
