# Generated by Django 4.0.5 on 2022-10-17 18:41

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('dfrm_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Facility name')),
                ('phone_number', phone_field.models.PhoneField(max_length=31, verbose_name='Phone number')),
                ('fax_number', phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Fax number')),
                ('street_address', models.CharField(max_length=100, verbose_name='Street address')),
                ('mailing_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mailing address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('zipcode', models.CharField(max_length=5, verbose_name='Zip Code')),
                ('facility_image', models.ImageField(blank=True, upload_to='images/facility/', verbose_name='Facility image')),
                ('administrative_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac_assist', to='dfrm_admin.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fac_manager', to='dfrm_admin.employee')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.RemoveField(
            model_name='department',
            name='office',
        ),
        migrations.RemoveField(
            model_name='division',
            name='office',
        ),
        migrations.AddField(
            model_name='subproject',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_div', to='dfrm_admin.division'),
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.AddField(
            model_name='department',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.facility'),
        ),
        migrations.AddField(
            model_name='division',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.facility'),
        ),
    ]
