# Generated by Django 4.0.5 on 2022-10-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('dfrm_admin', '0002_facility_remove_department_office_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='location',
        ),
        migrations.AlterField(
            model_name='department',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.facility'),
        ),
        migrations.AlterField(
            model_name='division',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.facility'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_div', to='dfrm_admin.division'),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
    ]
