# Generated by Django 4.0.5 on 2022-10-24 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_point_name'),
        ('dfrm_admin', '0004_alter_subproject_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='dfrm_admin.project'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='location',
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='locations', to='locations.location', verbose_name='Task location'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dfrm_admin.subproject'),
        ),
    ]
