# Generated by Django 4.0.5 on 2023-05-05 19:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_options_and_more'),
        ('locations', '0003_alter_location_geom_type'),
        ('dfrm_admin', '0005_alter_subproject_project_remove_task_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name__user__first_name', 'name__user__last_name']},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['name__name'], 'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AddField(
            model_name='employee',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fac_employees', to='dfrm_admin.facility', verbose_name='Duty Station'),
        ),
        migrations.AlterField(
            model_name='department',
            name='administrative_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_assist', to='dfrm_admin.employee', verbose_name='Administrative Assistant'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_image1',
            field=models.ImageField(upload_to='images/department/', verbose_name='Department Image'),
        ),
        migrations.AlterField(
            model_name='department',
            name='deputy_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_deputy', to='dfrm_admin.employee', verbose_name='Deputy Manager'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Department Desecription'),
        ),
        migrations.AlterField(
            model_name='department',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.facility', verbose_name='Department Office'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_manager', to='dfrm_admin.employee', verbose_name='Department Manager'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='division',
            name='administrative_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div_assist', to='dfrm_admin.employee', verbose_name='Administrative Assistant'),
        ),
        migrations.AlterField(
            model_name='division',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.department', verbose_name='Division Department'),
        ),
        migrations.AlterField(
            model_name='division',
            name='deputy_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div_deputy', to='dfrm_admin.employee', verbose_name='Deputy Division Director'),
        ),
        migrations.AlterField(
            model_name='division',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Division Desecription'),
        ),
        migrations.AlterField(
            model_name='division',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='div_director', to='dfrm_admin.employee', verbose_name='Division Director'),
        ),
        migrations.AlterField(
            model_name='division',
            name='division_image1',
            field=models.ImageField(upload_to='images/division/', verbose_name='Division Image'),
        ),
        migrations.AlterField(
            model_name='division',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.facility', verbose_name='Division Office'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Division Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Employeed (check for yes)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.userprofile', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfrm_admin.positionclass', verbose_name='Position Class'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Position Title'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='administrative_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac_assist', to='dfrm_admin.employee', verbose_name='Administrative Assistant'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_image',
            field=models.ImageField(upload_to='images/facility/', verbose_name='Facility Image'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='fax_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Fax Number'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='mailing_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mailing Address'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fac_manager', to='dfrm_admin.employee', verbose_name='Facility Manager'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='Facility Name'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=31, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='street_address',
            field=models.CharField(max_length=100, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.BooleanField(verbose_name='Active Project (check for yes)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(verbose_name='Project Created'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image1',
            field=models.ImageField(upload_to='images/project/', verbose_name='Project Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_leader',
            field=models.ManyToManyField(to='dfrm_admin.employee', verbose_name='Project Leader'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Subproject Description'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_div', to='dfrm_admin.division', verbose_name='Subproject Division'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Subproject Name'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='dfrm_admin.project', verbose_name='Parent Project'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sup', to='dfrm_admin.employee', verbose_name='Subproject Supervisor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Task Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='locations', to='locations.location', verbose_name='Task Location'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Task Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staff', to='dfrm_admin.employee', verbose_name='Task Staff'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dfrm_admin.subproject', verbose_name='Subproject'),
        ),
        migrations.AlterField(
            model_name='task',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sup', to='dfrm_admin.employee', verbose_name='Task Supervisor'),
        ),
    ]
