# Generated by Django 4.0.5 on 2023-05-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfrm_admin', '0006_alter_employee_options_alter_facility_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='key_staff',
            field=models.ManyToManyField(blank=True, null=True, to='dfrm_admin.employee', verbose_name='Management Staff'),
        ),
        migrations.AddField(
            model_name='division',
            name='managers',
            field=models.ManyToManyField(blank=True, null=True, to='dfrm_admin.employee', verbose_name='Managers'),
        ),
    ]
