# Generated by Django 4.0.5 on 2023-05-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfrm_admin', '0007_department_key_staff_division_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='key_staff',
            new_name='managers',
        ),
    ]
