# Generated by Django 4.0.5 on 2023-05-05 19:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organization',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='affiliation',
            field=models.CharField(choices=[('NPT', 'Nez Perce Tribe'), ('IDFG', 'Idaho Department of Fish and Game'), ('WDFW', 'Washington Department of Fish and Wildlife'), ('ODFW', 'Oregon Department of Fish and Wildlife'), ('USFWS', 'U.S. Fish and Wildlife Service'), ('USFS', 'U.S. Forest Service'), ('USACE', 'U.S. Army Core of Engineers'), ('NOAA', 'National Oceanic Atmospheric Administration'), ('BPA', 'Bonneville Power Administration'), ('NPCC', 'Northwest Power and Conservation Council'), ('Other', 'Other')], default='NPT', max_length=50, verbose_name='Affiliation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_updates',
            field=models.BooleanField(default=False, verbose_name='Email Updates (check for yes)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='images/profile/P7160105_fix.JPG', upload_to='images/profile/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='User name', on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to=settings.AUTH_USER_MODEL, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Work Phone'),
        ),
    ]
