# Generated by Django 4.0.5 on 2022-09-27 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Division name', max_length=300)),
                ('description', models.TextField(help_text='Division description')),
                ('division_image1', models.ImageField(blank=True, null=True, upload_to='images/division/')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_class', models.CharField(choices=[('Technician I', 'Technician I'), ('Technician II', 'Technician II'), ('Technician III', 'Technician III'), ('Professional I', 'Professional I'), ('Professional II', 'Professional II'), ('Professional III', 'Professional III'), ('Professional IV', 'Professional IV'), ('Professional V', 'Project Leader V'), ('Manager I', 'Manager I'), ('Manager II', 'Manager II'), ('Manager III', 'Manager III'), ('Manager IV', 'Manager IV'), ('Manager V', 'Manager V')], help_text='Position class', max_length=100)),
                ('title', models.CharField(help_text='Position title', max_length=50)),
                ('work_phone', phone_field.models.PhoneField(blank=True, help_text='Work phone number', max_length=31, null=True)),
                ('cell_phone', phone_field.models.PhoneField(blank=True, help_text='Cell phone number', max_length=31, null=True)),
                ('active', models.BooleanField(default=False, help_text='Is the employee actively employed?')),
                ('bio', models.TextField(help_text='Staff biography', null=True)),
                ('name', models.ForeignKey(help_text='Employee name', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=300)),
                ('description', models.TextField(help_text='Project description')),
                ('created', models.DateTimeField(help_text='When was the project created?')),
                ('active', models.BooleanField(help_text='Is the project currently active?')),
                ('project_image1', models.ImageField(blank=True, null=True, upload_to='images/project/')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.division')),
                ('project_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_lead', to='main.staff')),
                ('staff', models.ManyToManyField(blank=True, to='main.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Office name', max_length=100)),
                ('phone_number', phone_field.models.PhoneField(help_text='Phone number', max_length=31)),
                ('fax_number', phone_field.models.PhoneField(blank=True, help_text='Fax number', max_length=31, null=True)),
                ('address', models.CharField(help_text='Street address', max_length=100)),
                ('city', models.CharField(help_text='City', max_length=50)),
                ('state', models.CharField(help_text='State', max_length=50)),
                ('zipcode', models.CharField(help_text='Zip Code', max_length=5)),
                ('office_image', models.ImageField(blank=True, null=True, upload_to='images/office/')),
                ('administrative_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_assistant', to='main.staff')),
                ('office_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office', to='main.staff')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
            },
        ),
        migrations.AddField(
            model_name='division',
            name='administrative_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support', to='main.staff'),
        ),
        migrations.AddField(
            model_name='division',
            name='deputy_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deputy', to='main.staff'),
        ),
        migrations.AddField(
            model_name='division',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='main.staff'),
        ),
        migrations.AddField(
            model_name='division',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office', to='main.office'),
        ),
    ]
