# Generated by Django 4.0.5 on 2022-06-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_divisions_division_rename_projects_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='division',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='closed',
            new_name='inactive',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='name',
        ),
    ]
