# Generated by Django 4.0.5 on 2022-07-01 16:15

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_division_deputy_alter_division_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
