# Generated by Django 4.0.5 on 2022-08-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_division_phone_number_project_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='division_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/division/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/project/'),
        ),
    ]
