# Generated by Django 4.0.5 on 2022-10-14 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dfrm_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publish_date', models.DateField()),
                ('document_type', models.CharField(choices=[('Annual Report', 'Annual Report'), ('Journal Article', 'Journal Article'), ('Technical Memo', 'Technical Memo'), ('Presentation Slides', 'Presentation Slides'), ('Other', 'Other')], max_length=30)),
                ('keywords', models.CharField(max_length=60)),
                ('citation', models.TextField()),
                ('file', models.FileField(upload_to='documents/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('employee_authors', models.ManyToManyField(to='dfrm_admin.employee')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_upload', to='dfrm_admin.employee')),
            ],
        ),
    ]
