# Generated by Django 4.0.5 on 2022-10-14 21:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom_type', models.CharField(choices=[('Point', 'Point'), ('Linestring', 'Linestring'), ('Polygon', 'Polygon'), ('MultiPoint', 'MultiPoint'), ('MultiLineString', 'MultiLineString'), ('MultiPolygon', 'MultiPolygon'), ('GeometryCollection', 'GeometryCollection'), ('Raster', 'Raster')], max_length=30, verbose_name='Geometry Type')),
            ],
            options={
                'verbose_name': 'Geometry',
                'verbose_name_plural': 'Geometries',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Location Name')),
                ('geom_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='locations.geometry')),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='Linestring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
    ]
