# Generated by Django 4.0.5 on 2023-05-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_point_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geom_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='locations.geometry', verbose_name='Geometry Type'),
        ),
    ]
